version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'

  - package-ecosystem: 'pnpm'
    directory: '/src-capacitor'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'
