version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: 'pinia'
        update-types: ['version-update:semver-minor']
    labels:
      - 'dependency'
