version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: '/src-capacitor'
    schedule:
      interval: 'weekly'
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-dependencies:
        update-types: 
          - "patch"
    labels:
      - 'dependencies'
