/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/components/chart/ChartPage': RouteRecordInfo<
      '/dashboard/components/chart/ChartPage',
      '/dashboard/components/chart/ChartPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/components/DashboardCard': RouteRecordInfo<
      '/dashboard/components/DashboardCard',
      '/dashboard/components/DashboardCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/components/DashboardValue': RouteRecordInfo<
      '/dashboard/components/DashboardValue',
      '/dashboard/components/DashboardValue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/DashboardPage': RouteRecordInfo<
      '/dashboard/DashboardPage',
      '/dashboard/DashboardPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ErrorNotFound': RouteRecordInfo<
      '/ErrorNotFound',
      '/ErrorNotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/components/ExpenseCard': RouteRecordInfo<
      '/refuels/components/ExpenseCard',
      '/refuels/components/ExpenseCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/components/RefuelCard': RouteRecordInfo<
      '/refuels/components/RefuelCard',
      '/refuels/components/RefuelCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/components/RefuelCardSkeleton': RouteRecordInfo<
      '/refuels/components/RefuelCardSkeleton',
      '/refuels/components/RefuelCardSkeleton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/ExpenseForm': RouteRecordInfo<
      '/refuels/ExpenseForm',
      '/refuels/ExpenseForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/FilterRefuelsForm': RouteRecordInfo<
      '/refuels/FilterRefuelsForm',
      '/refuels/FilterRefuelsForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/layouts/RefuelLayout': RouteRecordInfo<
      '/refuels/layouts/RefuelLayout',
      '/refuels/layouts/RefuelLayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/RefuelForm': RouteRecordInfo<
      '/refuels/RefuelForm',
      '/refuels/RefuelForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refuels/RefuelsPage': RouteRecordInfo<
      '/refuels/RefuelsPage',
      '/refuels/RefuelsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/SettingsPage': RouteRecordInfo<
      '/settings/SettingsPage',
      '/settings/SettingsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/SupportPage': RouteRecordInfo<
      '/support/SupportPage',
      '/support/SupportPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/components/VehicleCard': RouteRecordInfo<
      '/vehicles/components/VehicleCard',
      '/vehicles/components/VehicleCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/layouts/VehicleLayout': RouteRecordInfo<
      '/vehicles/layouts/VehicleLayout',
      '/vehicles/layouts/VehicleLayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/VehicleForm': RouteRecordInfo<
      '/vehicles/VehicleForm',
      '/vehicles/VehicleForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/VehiclesPage': RouteRecordInfo<
      '/vehicles/VehiclesPage',
      '/vehicles/VehiclesPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/dashboard/components/chart/ChartPage.vue': {
      routes:
        | '/dashboard/components/chart/ChartPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/components/DashboardCard.vue': {
      routes:
        | '/dashboard/components/DashboardCard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/components/DashboardValue.vue': {
      routes:
        | '/dashboard/components/DashboardValue'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/DashboardPage.vue': {
      routes:
        | '/dashboard/DashboardPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ErrorNotFound.vue': {
      routes:
        | '/ErrorNotFound'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/components/ExpenseCard.vue': {
      routes:
        | '/refuels/components/ExpenseCard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/components/RefuelCard.vue': {
      routes:
        | '/refuels/components/RefuelCard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/components/RefuelCardSkeleton.vue': {
      routes:
        | '/refuels/components/RefuelCardSkeleton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/ExpenseForm.vue': {
      routes:
        | '/refuels/ExpenseForm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/FilterRefuelsForm.vue': {
      routes:
        | '/refuels/FilterRefuelsForm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/layouts/RefuelLayout.vue': {
      routes:
        | '/refuels/layouts/RefuelLayout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/RefuelForm.vue': {
      routes:
        | '/refuels/RefuelForm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/refuels/RefuelsPage.vue': {
      routes:
        | '/refuels/RefuelsPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/SettingsPage.vue': {
      routes:
        | '/settings/SettingsPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/support/SupportPage.vue': {
      routes:
        | '/support/SupportPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicles/components/VehicleCard.vue': {
      routes:
        | '/vehicles/components/VehicleCard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicles/layouts/VehicleLayout.vue': {
      routes:
        | '/vehicles/layouts/VehicleLayout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicles/VehicleForm.vue': {
      routes:
        | '/vehicles/VehicleForm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicles/VehiclesPage.vue': {
      routes:
        | '/vehicles/VehiclesPage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
